# Generated by Django 6.0.4 on 2026-04-12 08:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_number', models.CharField(max_length=50)),
                ('document_type', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[A-Za-z]{1,5}$', '1-5 alpha characters only')])),
                ('doc_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('uri', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('employee_name', models.TextField(blank=True, default='')),
                ('employee_dob', models.DateField(blank=True, null=True)),
                ('file_relative_path', models.TextField()),
                ('file_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('digilocker_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents',
                'indexes': [models.Index(condition=models.Q(('digilocker_enabled', True), ('is_active', True)), fields=['authorization_number', 'document_type'], name='idx_documents_lookup'), models.Index(fields=['uri'], name='idx_documents_uri'), models.Index(fields=['doc_id'], name='idx_documents_doc_id')],
                'constraints': [models.UniqueConstraint(fields=('authorization_number', 'document_type'), name='uq_documents_business'), models.CheckConstraint(condition=models.Q(models.Q(('doc_id__isnull', True), ('uri__isnull', True)), models.Q(('doc_id__isnull', False), ('uri__isnull', False)), _connector='OR'), name='chk_doc_id_uri_pair')],
            },
        ),
        migrations.CreateModel(
            name='IntegrityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(max_length=30)),
                ('stored_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('calculated_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('file_path', models.TextField(blank=True, default='')),
                ('action_taken', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issuer.document')),
            ],
            options={
                'db_table': 'integrity_logs',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_number', models.CharField(blank=True, default='', max_length=50)),
                ('document_type', models.CharField(blank=True, default='', max_length=5)),
                ('txn_id', models.CharField(blank=True, default='', max_length=100)),
                ('digilocker_id', models.CharField(blank=True, default='', max_length=255)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('response_status', models.SmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issuer.document')),
            ],
            options={
                'db_table': 'access_logs',
                'indexes': [models.Index(fields=['created_at'], name='idx_access_logs_created'), models.Index(fields=['txn_id'], name='idx_access_logs_txn')],
            },
        ),
    ]
