# Generated by Django 6.0.4 on 2026-04-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0003_document_access_count_document_application_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integritylog',
            name='authorization_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='integritylog',
            name='calculated_file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integritylog',
            name='digilocker_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='integritylog',
            name='digilocker_txn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='integritylog',
            name='document_type',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='integritylog',
            name='request_ip',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='integritylog',
            name='stored_file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
