# Generated by Django 6.0.4 on 2026-04-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0004_integritylog_authorization_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='file_checksum',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='file_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='requested_mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
