# Generated by Django 6.0.4 on 2026-04-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0007_reference_schema_alignment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='chk_file_size',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='idx_auth_lookup',
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(condition=models.Q(('digilocker_enabled', True), ('is_active', True)), fields=['authorization_number', 'document_type'], name='idx_auth_lookup'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('file_size_bytes__isnull', True), ('file_size_bytes__gt', 0), _connector='OR'), name='chk_file_size'),
        ),
    ]
