# Generated by Django 6.0.4 on 2026-05-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0008_remove_document_chk_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='external_system_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
