# Generated by Django 6.0.4 on 2026-05-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0009_alter_document_external_system_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(max_length=30),
        ),
    ]
