# Generated by Django 6.0.4 on 2026-05-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0010_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='chk_authorization_date',
        ),
    ]
