# Generated by Django 6.0.4 on 2026-05-21 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0011_remove_document_chk_authorization_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='authorization_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='employee_name',
            field=models.CharField(max_length=255),
        ),
    ]
