# Generated by Django 6.0.4 on 2026-05-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0012_alter_document_authorization_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(max_length=30),
        ),
    ]
