# Generated by Django 6.0.4 on 2026-05-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0013_fix_document_type_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslog',
            name='document_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
